# Generated by Django 4.2.28 on 2026-02-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category'], name='idx_item_category'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status'], name='idx_item_status'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['owner', 'is_deleted'], name='idx_item_owner_active'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['created_at'], name='idx_item_created'),
        ),
    ]
